// This file implements the FHIR-specific FHIRPath `htmlChecks()` function.
// See https://build.fhir.org/fhirpath.html#fn-htmlChecks and the narrative
// rules it links to: https://build.fhir.org/narrative.html#rules
//
// The narrative "is contained in general XML"
// (https://build.fhir.org/narrative.html#xhtml), so the content must be
// well-formed XHTML: every element closed, every attribute value quoted and
// only legal XML characters. See docs/html-checks.md for the full rule list
// and for how the rules are interpreted.

const { TypeInfo, ResourceNode } = require("./types");

const engine = {};


/**
 * Builds a Set from an array of strings.
 * IE11 (the browser build target, see browser-build/webpack.config.js) does
 * not support `new Set(iterable)`: it accepts the argument and silently
 * ignores it, so an iterable argument would yield an empty Set rather than a
 * failure. The entries are therefore added one by one, as in src/types.js. An
 * empty allow list here would make every narrative invalid.
 * @param {Array<string>} names - the entries to add.
 * @returns {Set<string>}
 */
function toSet(names) {
  const set = new Set();
  for (let i = 0; i < names.length; ++i) {
    set.add(names[i]);
  }
  return set;
}


// Element names allowed inside FHIR narrative XHTML.
// The FHIR narrative rules allow the basic formatting elements from chapters
// 7-11 and 15 of HTML 4.0, plus anchors and images. Image maps (`map` and
// `area`) belong to chapter 13 and are therefore not included.
// `address`, `bdo` and `kbd` come from those chapters (7, 8 and 9), even
// though the R4 `txt-1` XPath does not enumerate them; see
// docs/html-checks.md.
const ALLOWED_ELEMENT_LIST = [
  "p", "br", "div", "h1", "h2", "h3", "h4", "h5", "h6", "a", "span", "b",
  "em", "i", "strong", "small", "big", "tt", "dfn", "q", "var", "abbr",
  "acronym", "cite", "blockquote", "hr", "address", "bdo", "kbd", "sub",
  "sup", "ul", "ol", "li", "dl", "dt", "dd", "pre", "table", "caption",
  "colgroup", "col", "thead", "tr", "tfoot", "tbody", "th", "td", "code",
  "samp", "img"
];
const ALLOWED_ELEMENTS = toSet(ALLOWED_ELEMENT_LIST);


// Attribute names allowed on any of the elements above.
// The unprefixed `xmlns` is how FHIR narrative declares the XHTML namespace,
// and well-formed XML may redeclare the default namespace on any element, so
// it is accepted everywhere. The declaration is not required, but its value
// must be the XHTML namespace wherever it appears, see checkHtml() and
// docs/html-checks.md.
// Namespace-prefixed names are not supported, i.e. neither `xmlns:<prefix>`
// nor prefixed attribute names such as `xml:lang` and `xml:space`. Besides
// keeping the checks free of namespace handling, this keeps the set of
// accepted attribute names finite, which is what bounds the duplicate scan in
// checkHtml(): an unbounded family such as `xmlns:a1`, `xmlns:a2`, ... would
// let a single start tag carry an arbitrary number of distinct accepted
// attributes and turn that scan quadratic. No spec narrative uses them - no
// narrative used in the spec profiles has an attribute name containing a
// colon.
// The table attributes below (`span`, `align`, `valign`, `char`, `charoff`,
// `abbr`, `axis`, `headers`, `scope`, `rowspan`, `colspan`) are deliberately
// kept global, as they are in the R4 `txt-1` XPath, which tests attribute
// names document-wide, so that e.g. `<p rowspan="2">` is accepted; see
// docs/html-checks.md.
// `width` is the one table attribute that is not global here: it is not a
// global attribute in HTML 4.0 - it belongs to the table elements and to
// `img` - so it is scoped per element below.
const ALLOWED_ATTR_LIST = [
  "title", "style", "class", "id", "lang", "dir", "accesskey", "tabindex",
  // namespaces
  "xmlns",
  // tables
  "span", "align", "valign", "char", "charoff", "abbr", "axis",
  "headers", "scope", "rowspan", "colspan"
];
const ALLOWED_ATTRS = toSet(ALLOWED_ATTR_LIST);


// Attribute names allowed only on a particular element ("element.attribute").
// The narrative rules allow anchors with either `name` or `href`; these are
// the only anchor-specific attributes, and neither of them is required. The
// `txt-1` human text, "`<a>` elements (either name or href)", enumerates the
// permitted elements and attributes, so it is read as an allow list rather
// than as a requirement - which is how the `txt-1` XPath reads it too, and
// narratives generated by the FHIR publisher do contain anchors without
// either attribute (see test/resources/r4/observation-example.json).
// Attributes that are global to the basic formatting elements remain covered
// above, including the default `xmlns` declaration.
// The image-map hooks of `img`, `usemap` and `ismap`, belong to chapter 13
// and can only refer to a `map` that is rejected anyway, so they are not
// accepted. Neither is `pre.space`: a bare `space` attribute exists neither
// in HTML 4.0 nor in the R4 `txt-1` XPath, and the prefixed `xml:space` is
// rejected as well, so neither spelling is accepted.
const ALLOWED_ELEMENT_ATTR_LIST = [
  "a.href", "a.name",
  "img.src", "img.border", "img.alt", "img.longdesc", "img.height",
  "img.width",
  "blockquote.cite", "q.cite",
  "table.summary", "table.width", "table.border", "table.frame",
  "table.rules", "table.cellspacing", "table.cellpadding",
  "col.width", "colgroup.width", "th.width", "td.width", "td.nowrap"
];
const ALLOWED_ELEMENT_ATTRS = toSet(ALLOWED_ELEMENT_ATTR_LIST);


// The five character entities predefined by XML. FHIR narrative explicitly
// forbids HTML entities such as `&nbsp;` (Unicode characters or numeric
// character references must be used instead).
const XML_ENTITIES = toSet(["amp", "lt", "gt", "quot", "apos"]);


// The only namespace FHIR narrative may declare: "the XHTML is contained in
// general XML", and the JSON encoding of a narrative is
// `"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">text</div>"`, see
// https://build.fhir.org/narrative.html#xhtml
const XHTML_NS = "http://www.w3.org/1999/xhtml";


// Character codes used by the scanner.
const CH_TAB = 9;
const CH_LF = 10;
const CH_CR = 13;
const CH_SPACE = 32;
const CH_BANG = 33;       // !
const CH_QUOT = 34;       // "
const CH_HASH = 35;       // #
const CH_AMP = 38;        // &
const CH_APOS = 39;       // '
const CH_SLASH = 47;      // /
const CH_ZERO = 48;       // 0
const CH_NINE = 57;       // 9
const CH_SEMI = 59;       // ;
const CH_LT = 60;         // <
const CH_EQ = 61;         // =
const CH_GT = 62;         // >
const CH_QUESTION = 63;   // ?
const CH_UPPER_A = 65;    // A
const CH_UPPER_F = 70;    // F
const CH_UPPER_Z = 90;    // Z
const CH_RBRACKET = 93;   // ]
const CH_LOWER_A = 97;    // a
const CH_LOWER_F = 102;   // f
const CH_LOWER_X = 120;   // x
const CH_LOWER_Z = 122;   // z

// Bounds of the XML 1.0 `Char` production, see
// https://www.w3.org/TR/xml/#charsets
const CP_SURROGATE_HIGH_MIN = 0xD800;
const CP_SURROGATE_HIGH_MAX = 0xDBFF;
const CP_SURROGATE_LOW_MIN = 0xDC00;
const CP_SURROGATE_LOW_MAX = 0xDFFF;
const CP_NONCHAR_MIN = 0xFFFE;
const CP_SUPPLEMENTARY_MIN = 0x10000;
const CP_MAX = 0x10FFFF;


/**
 * Checks if the character code is a decimal digit.
 * @param {number} c - character code.
 * @returns {boolean}
 */
function isDigit(c) {
  return c >= CH_ZERO && c <= CH_NINE;
}


/**
 * Returns the numeric value of a hexadecimal digit.
 * @param {number} c - character code.
 * @returns {number} the value 0-15, or -1 if `c` is not a hexadecimal digit.
 */
function hexValue(c) {
  if (c >= CH_ZERO && c <= CH_NINE) {
    return c - CH_ZERO;
  }
  if (c >= CH_LOWER_A && c <= CH_LOWER_F) {
    return c - CH_LOWER_A + 10;
  }
  if (c >= CH_UPPER_A && c <= CH_UPPER_F) {
    return c - CH_UPPER_A + 10;
  }
  return -1;
}


/**
 * Checks if the character code is an ASCII letter.
 * @param {number} c - character code.
 * @returns {boolean}
 */
function isAlpha(c) {
  return (c >= CH_LOWER_A && c <= CH_LOWER_Z) ||
    (c >= CH_UPPER_A && c <= CH_UPPER_Z);
}


/**
 * Checks if the character is XML whitespace, i.e. one of the four characters
 * matched by the XML `S` production
 * (https://www.w3.org/TR/xml/#sec-common-syn). Used inside markup, where a C0
 * control character is not a separator but an illegal XML character.
 * @param {number} c - character code.
 * @returns {boolean}
 */
function isXmlSpace(c) {
  return c === CH_SPACE || c === CH_LF || c === CH_TAB || c === CH_CR;
}


/**
 * Checks whether a code point is legal in XML (the `Char` production).
 * @param {number} cp - the code point.
 * @returns {boolean}
 */
function isXmlCodePoint(cp) {
  return cp === CH_TAB || cp === CH_LF || cp === CH_CR ||
    (cp >= CH_SPACE && cp < CP_SURROGATE_HIGH_MIN) ||
    (cp > CP_SURROGATE_LOW_MAX && cp < CP_NONCHAR_MIN) ||
    (cp >= CP_SUPPLEMENTARY_MIN && cp <= CP_MAX);
}


/**
 * Classifies a character for XML validity. Must only be called when the code
 * unit at `i` is below 0x20 or at/above 0xD800 -- every other code unit is a
 * legal XML character.
 * @param {string} text - the text being scanned.
 * @param {number} i - index of the code unit to classify.
 * @param {number} len - index to stop scanning at.
 * @returns {number} the number of *extra* UTF-16 code units the character
 *   occupies (0 for a BMP character, 1 for a surrogate pair), or -1 when the
 *   character is not legal in XML.
 */
function extraUnitsForXmlChar(text, i, len) {
  const c = text.charCodeAt(i);
  if (c < CH_SPACE) {
    return c === CH_TAB || c === CH_LF || c === CH_CR ? 0 : -1;
  }
  if (c <= CP_SURROGATE_HIGH_MAX) {
    const c2 = i + 1 < len ? text.charCodeAt(i + 1) : 0;
    return c2 >= CP_SURROGATE_LOW_MIN && c2 <= CP_SURROGATE_LOW_MAX ? 1 : -1;
  }
  if (c <= CP_SURROGATE_LOW_MAX) {
    // Unpaired low surrogate.
    return -1;
  }
  return c >= CP_NONCHAR_MIN ? -1 : 0;
}


/**
 * Checks that text[start, end) contains only legal XML characters.
 * @param {string} text - the text being scanned.
 * @param {number} start - index of the first character to check.
 * @param {number} end - index just past the last character to check.
 * @returns {boolean} true if all characters are legal in XML.
 */
function checkXmlChars(text, start, end) {
  for (let i = start; i < end; ++i) {
    const c = text.charCodeAt(i);
    if (c < CH_SPACE || c >= CP_SURROGATE_HIGH_MIN) {
      const extra = extraUnitsForXmlChar(text, i, end);
      if (extra === -1) {
        return false;
      }
      i += extra;
    }
  }
  return true;
}


/**
 * Checks whether the given attribute is allowed on the given element. Both
 * allow lists hold unprefixed names only (including the default `xmlns`
 * declaration), so a namespace-prefixed or `xml:*` name can never match.
 * @param {string} elementName - the (case-sensitive) element name.
 * @param {string} attrName - the (case-sensitive) attribute name.
 * @returns {boolean}
 */
function isAllowedAttr(elementName, attrName) {
  return ALLOWED_ATTRS.has(attrName) ||
    ALLOWED_ELEMENT_ATTRS.has(elementName + "." + attrName);
}


/**
 * Checks whether text[start, end) is exactly the XHTML namespace URI.
 * The value is compared code unit by code unit, so that no substring is
 * allocated for an attribute value that is usually not a namespace
 * declaration at all, and so that the comparison stays independent of
 * `String.prototype.startsWith()`, whose IE11 polyfill (see src/polyfill.js)
 * keeps searching past `start` when the value does not match there.
 * The raw text is compared: a value spelled with character references, e.g.
 * `http&#58;//www.w3.org/1999/xhtml`, does not match, see docs/html-checks.md.
 * @param {string} text - the text being scanned.
 * @param {number} start - index of the first character of the value.
 * @param {number} end - index just past the last character of the value.
 * @returns {boolean}
 */
function isXhtmlNs(text, start, end) {
  if (end - start !== XHTML_NS.length) {
    return false;
  }
  for (let i = 0; i < XHTML_NS.length; ++i) {
    if (text.charCodeAt(start + i) !== XHTML_NS.charCodeAt(i)) {
      return false;
    }
  }
  return true;
}


/**
 * Scans a character reference starting at `start` (which must point at `&`).
 * Only the five XML entities and numeric character references denoting a
 * legal XML character are accepted.
 * @param {string} text - the text being scanned.
 * @param {number} start - index of the `&` character.
 * @param {number} end - index to stop scanning at.
 * @returns {number} index just past the terminating `;`, or -1 if the
 *   character reference is not valid.
 */
function scanCharRef(text, start, end) {
  let i = start + 1;
  if (i < end && text.charCodeAt(i) === CH_HASH) {
    ++i;
    let cp = 0;
    let digitsStart;
    if (i < end && text.charCodeAt(i) === CH_LOWER_X) {
      digitsStart = ++i;
      for (;;) {
        const v = i < end ? hexValue(text.charCodeAt(i)) : -1;
        if (v === -1) {
          break;
        }
        cp = cp * 16 + v;
        if (cp > CP_MAX) {
          return -1;
        }
        ++i;
      }
    } else {
      digitsStart = i;
      while (i < end && isDigit(text.charCodeAt(i))) {
        cp = cp * 10 + (text.charCodeAt(i) - CH_ZERO);
        if (cp > CP_MAX) {
          return -1;
        }
        ++i;
      }
    }
    if (i === digitsStart || !isXmlCodePoint(cp)) {
      return -1;
    }
  } else {
    const nameStart = i;
    while (i < end && isAlpha(text.charCodeAt(i))) {
      ++i;
    }
    if (i === nameStart ||
      !XML_ENTITIES.has(text.substring(nameStart, i))) {
      return -1;
    }
  }
  return i < end && text.charCodeAt(i) === CH_SEMI ? i + 1 : -1;
}


/**
 * Validates FHIR narrative XHTML in a single pass, without building a DOM.
 *
 * The scanner enforces XML well-formedness -- matching tags with no void
 * element shorthand, quoted attribute values with no raw `<`, legal XML
 * characters and character references, no `--` inside comments, no literal
 * `]]>` in character data, and no processing instructions, DOCTYPE
 * declarations or CDATA sections -- together with the FHIR narrative rules
 * (element/attribute allow lists, the XHTML namespace for every `xmlns`
 * declaration, and the requirement that the `div` has some non-whitespace
 * content).
 *
 * @param {string} text - the XHTML to check.
 * @param {boolean} isFragment - when true, `text` is treated as the *content*
 *   of a `div` (used for items of type `string`); when false, `text` must be
 *   a document whose single root element is a `div`.
 * @returns {boolean} true if the rules around HTML usage are met.
 */
function checkHtml(text, isFragment) {
  const len = text.length;
  // Names of the currently open elements.
  const stack = [];
  // Attribute names of the start tag being scanned (reused for every tag to
  // avoid per-tag allocations). A linear scan is enough to detect duplicates:
  // every accepted name comes from the allow lists, so a start tag can carry
  // at most a few dozen distinct attributes before a repeated (or rejected)
  // name ends the scan.
  const attrNames = [];
  // Whether a root `div` element has been seen (document mode only).
  let rootSeen = false;
  // Whether some non-whitespace content (text or an image) has been found.
  let hasContent = false;
  let i = 0;

  while (i < len) {
    if (text.charCodeAt(i) !== CH_LT) {
      // Character data up to the next `<`.
      if (!isFragment && stack.length === 0) {
        // In document mode, only whitespace may appear outside the root
        // element: in JSON "the characters between the first '>' and the last
        // '<' delimiters is the content of the <div> element".
        while (i < len) {
          const c = text.charCodeAt(i);
          if (c === CH_LT) {
            break;
          }
          if (!isXmlSpace(c)) {
            return false;
          }
          ++i;
        }
        continue;
      }
      while (i < len) {
        const c = text.charCodeAt(i);
        if (c > CH_SPACE) {
          if (c === CH_LT) {
            break;
          }
          if (c === CH_AMP) {
            const next = scanCharRef(text, i, len);
            if (next === -1) {
              return false;
            }
            // A character reference always counts as content, including one
            // that denotes a whitespace character: Unicode characters such as
            // `&#160;` substitute for HTML entities, and escaping a character
            // is taken as a statement that it is significant. This is more
            // permissive than normalize-space() in the R4 txt-2 XPath, see
            // docs/html-checks.md.
            hasContent = true;
            i = next;
            continue;
          }
          if (c === CH_RBRACKET) {
            if (text.startsWith("]]>", i)) {
              // XML does not allow a literal `]]>` in character data, and
              // there is no CDATA section available to escape it; `]]&gt;`
              // must be used instead.
              return false;
            }
          } else if (c >= CP_SURROGATE_HIGH_MIN) {
            const extra = extraUnitsForXmlChar(text, i, len);
            if (extra === -1) {
              return false;
            }
            i += extra;
          }
          hasContent = true;
        } else if (!isXmlSpace(c)) {
          // A C0 control character other than tab, LF or CR is not a legal
          // XML character.
          return false;
        }
        ++i;
      }
      continue;
    }

    const c1 = i + 1 < len ? text.charCodeAt(i + 1) : 0;

    if (c1 === CH_QUESTION) {
      // Processing instructions (e.g. `<?xml ... ?>`) are not allowed:
      // see https://build.fhir.org/narrative.html#xhtml
      return false;
    }

    if (c1 === CH_BANG) {
      if (text.startsWith("<!--", i)) {
        if (!isFragment && stack.length === 0) {
          // Nothing but whitespace may appear outside the root element.
          return false;
        }
        const end = text.indexOf("-->", i + 4);
        if (end === -1) {
          return false;
        }
        // XML does not allow `--` inside a comment. `indexOf("--")` cannot run
        // past `end`, because the closing `-->` itself starts with `--`, so
        // this stays bounded by the comment. A body ending in `-` needs no
        // check of its own: that `-` is immediately followed by the `-` that
        // starts `-->`, so it is already found as a `--` before `end`.
        if (text.indexOf("--", i + 4) < end ||
          !checkXmlChars(text, i + 4, end)) {
          return false;
        }
        i = end + 3;
        continue;
      }
      // `<!DOCTYPE ...>`, `<![CDATA[ ... ]]>` and any other declaration are
      // not allowed in FHIR narrative XHTML.
      return false;
    }

    if (c1 === CH_SLASH) {
      // End tag.
      let j = i + 2;
      const nameStart = j;
      while (j < len) {
        const c = text.charCodeAt(j);
        if (isXmlSpace(c) || c === CH_GT) {
          break;
        }
        ++j;
      }
      const name = text.substring(nameStart, j);
      while (j < len && isXmlSpace(text.charCodeAt(j))) {
        ++j;
      }
      if (j >= len || text.charCodeAt(j) !== CH_GT) {
        return false;
      }
      if (stack.length === 0 || stack[stack.length - 1] !== name) {
        // XHTML has no void-element shorthand: every element must be closed
        // explicitly (`<br></br>`) or self-closed (`<br/>`), so a mismatched
        // or unexpected end tag is always an error.
        return false;
      }
      stack.pop();
      i = j + 1;
      continue;
    }

    // Start tag.
    let j = i + 1;
    const nameStart = j;
    while (j < len) {
      const c = text.charCodeAt(j);
      if (isXmlSpace(c) || c === CH_SLASH || c === CH_GT) {
        break;
      }
      ++j;
    }
    if (j === nameStart) {
      return false;
    }
    const name = text.substring(nameStart, j);
    if (!ALLOWED_ELEMENTS.has(name)) {
      return false;
    }
    if (!isFragment && stack.length === 0) {
      // The root element of an xhtml value must be a `div`, and there may be
      // only one root element.
      if (rootSeen || name !== "div") {
        return false;
      }
      rootSeen = true;
    }

    attrNames.length = 0;
    let selfClosing = false;
    for (;;) {
      const wsStart = j;
      while (j < len && isXmlSpace(text.charCodeAt(j))) {
        ++j;
      }
      if (j >= len) {
        return false;
      }
      let c = text.charCodeAt(j);
      if (c === CH_GT) {
        ++j;
        break;
      }
      if (c === CH_SLASH) {
        ++j;
        if (j >= len || text.charCodeAt(j) !== CH_GT) {
          return false;
        }
        ++j;
        selfClosing = true;
        break;
      }
      // XML requires whitespace before every attribute:
      // `STag ::= '<' Name (S Attribute)* S? '>'`, so `<p title="a"class="c">`
      // is not well-formed. The `>` and `/>` branches above have already been
      // taken when nothing but the tag end follows the element name.
      if (j === wsStart) {
        return false;
      }
      const attrStart = j;
      while (j < len) {
        c = text.charCodeAt(j);
        if (isXmlSpace(c) || c === CH_EQ || c === CH_SLASH || c === CH_GT) {
          break;
        }
        ++j;
      }
      if (j === attrStart) {
        return false;
      }
      const attrName = text.substring(attrStart, j);
      if (!isAllowedAttr(name, attrName) ||
        attrNames.indexOf(attrName) !== -1) {
        return false;
      }
      attrNames.push(attrName);
      while (j < len && isXmlSpace(text.charCodeAt(j))) {
        ++j;
      }
      // XHTML does not allow attribute minimization: every attribute must
      // have an explicit value (e.g. `nowrap="nowrap"`, not `nowrap`).
      if (j >= len || text.charCodeAt(j) !== CH_EQ) {
        return false;
      }
      ++j;
      while (j < len && isXmlSpace(text.charCodeAt(j))) {
        ++j;
      }
      // XHTML requires every attribute value to be quoted. Unquoted values
      // are rejected: they are not well-formed XML, and their terminator is
      // ambiguous -- `<img src=a/>` means src="a/" to an HTML tokenizer but
      // is a self-closing tag in XML.
      c = j < len ? text.charCodeAt(j) : 0;
      if (c !== CH_QUOT && c !== CH_APOS) {
        return false;
      }
      const valueStart = ++j;
      for (;;) {
        if (j >= len) {
          return false;
        }
        const cc = text.charCodeAt(j);
        if (cc === c) {
          break;
        }
        if (cc === CH_LT) {
          // XML does not allow a raw `<` in an attribute value.
          return false;
        }
        if (cc === CH_AMP) {
          const next = scanCharRef(text, j, len);
          if (next === -1) {
            return false;
          }
          j = next;
          continue;
        }
        if (cc < CH_SPACE || cc >= CP_SURROGATE_HIGH_MIN) {
          const extra = extraUnitsForXmlChar(text, j, len);
          if (extra === -1) {
            return false;
          }
          j += extra;
        }
        ++j;
      }
      // A narrative is XHTML, so a default namespace declaration may only
      // declare the XHTML namespace - on the root `div` as well as on any
      // descendant that redeclares it. Without this check the element allow
      // list would be applied to elements that are not XHTML at all. The
      // declaration itself stays optional: `narrative.html` shows it on the
      // `div` in the JSON encoding, but a narrative that declares nothing is
      // still accepted, see docs/html-checks.md. `j` is the index of the
      // closing quote, so the value is text[valueStart, j).
      if (attrName === "xmlns" && !isXhtmlNs(text, valueStart, j)) {
        return false;
      }
      ++j;
    }

    if (name === "img" && attrNames.indexOf("src") !== -1) {
      // "The div element SHALL have some non-whitespace content (text or an
      // image)". The R4 txt-2 XPath is precise about what counts as an image:
      // `descendant::text()[normalize-space(.)!=''] or descendant::h:img[@src]`
      // -- an image only counts when it has a src.
      hasContent = true;
    }
    if (!selfClosing) {
      stack.push(name);
    }
    i = j;
  }

  if (stack.length !== 0 || (!isFragment && !rootSeen)) {
    return false;
  }
  // "The div element SHALL have some non-whitespace content (text or an
  // image)": https://build.fhir.org/narrative.html#xhtml. This is required by
  // the Narrative.div txt-2 invariant, whose FHIRPath expression is
  // `htmlChecks()` in STU3, R4 and R5.
  return hasContent;
}


/**
 * Implements the FHIR-specific FHIRPath `htmlChecks()` function.
 *
 * When invoked on a single `xhtml` element, returns true if the rules around
 * HTML usage are met, and false if they are not. When invoked on an item of
 * type `string`, the contents of the string are parsed as the content of a
 * `div`, and the function returns false if the string does not parse as valid
 * HTML or fails the rules around HTML usage. The return value is empty on any
 * other kind of element or if invoked on a collection of elements.
 *
 * `System.String` and the FHIR `string` type together with the types derived
 * from it (`code`, `id` and `markdown` in every supported model) are the
 * `string` overload, which matches how the FHIR type hierarchy is used
 * elsewhere in this library (`Patient.gender is FHIR.string` is true).
 * The `uri`-derived types (`uri`, `url`, `canonical`, `oid`, `uuid`) are not
 * derived from `string` and therefore still return an empty collection, and
 * neither is `xhtml`, so the two overloads stay disjoint.
 *
 * The spec describes the `string` overload as parsing "as valid HTML", but the
 * string is defined as "the content of a div", i.e. narrative content, and
 * narrative content is XHTML ("the XHTML is contained in general XML",
 * https://build.fhir.org/narrative.html#xhtml). A single strict XHTML rule set
 * is therefore applied to both overloads.
 *
 * Note that this function only validates the narrative; it is not an HTML
 * sanitizer and must not be relied upon as a defense against XSS.
 *
 * See https://build.fhir.org/fhirpath.html#fn-htmlChecks
 * @param {Array} coll - the input collection.
 * @returns {boolean|[]} true/false when the input is a single `xhtml`,
 *   `System.String`, `FHIR.string` or `string`-derived item, an empty
 *   collection otherwise.
 */
engine.htmlChecksFn = function (coll) {
  if (coll.length !== 1) {
    return [];
  }
  const node = coll[0];
  const isResourceNode = node instanceof ResourceNode;
  const value = isResourceNode ? node.data : node;
  if (typeof value !== "string") {
    return [];
  }
  if (!isResourceNode) {
    // A plain string value is always System.String; going through
    // TypeInfo.fromValue() would allocate a TypeInfo and run a regexp.
    return checkHtml(value, true);
  }
  const typeInfo = node.getTypeInfo();
  const namespace = typeInfo.namespace;
  if (namespace === TypeInfo.FHIR) {
    const name = typeInfo.name;
    if (name === "xhtml") {
      return checkHtml(value, false);
    }
    // The name comparison keeps `string` itself off the type hierarchy walk,
    // which is only reached for the types that used to return an empty
    // collection right away. The model is taken from the node (where
    // getTypeInfo() gets it from as well) rather than from the invocation
    // context, so that the result does not depend on how the function is
    // called.
    if (name === "string" || TypeInfo.isType(name, "string", node.model)) {
      return checkHtml(value, true);
    }
  } else if (namespace === TypeInfo.System && typeInfo.name === "String") {
    return checkHtml(value, true);
  }
  return [];
};


// Exported for unit tests only; not part of the public API. The allow lists
// are returned as fresh arrays, so that they cannot be modified from outside
// (adding e.g. `script` to one of the Sets would weaken every later check).
engine._checkHtml = checkHtml;
engine._allowedElements = () => ALLOWED_ELEMENT_LIST.slice();
engine._allowedAttrs = () => ALLOWED_ATTR_LIST.slice();
engine._allowedElementAttrs = () => ALLOWED_ELEMENT_ATTR_LIST.slice();

module.exports = engine;
